version: '3.8'

services:
  # Service for the PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: openmusic_db
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - openmusic-data:/var/lib/postgresql/data

  # Service for the Node.js Application
  app:
    container_name: openmusic_api
    build: . # Build the image from the Dockerfile in the current directory
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db # Wait for the db service to start before starting the app
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=db # Important: The host is now the service name 'db'
      - PGPORT=${PGPORT}
      - HOST=${HOST}
      - PORT=${PORT}

volumes:
  openmusic-data: